### ISSUE TITLE
Error message subtitle for industry construction failure is nondescript

### ISSUE THREAD

**Issue by James103** [2TallTyler/improved_town_industries#1]
## Versions used
OpenTTD: 1.10.2
NewGRF:
```
54540301|1899C0EE609AFD837091F9BF9E64CEE2|improved_town_layouts-1.1.2\improved_town_layouts.grf = 0 0 1 1 1
54540401|2B9CD4A272177B792F2E68BA43C254B9|improved_town_industries-1.0.0\improved_town_industries.grf = 0 1 1 0
```

## Expected result
The subtitle of the error message is more descriptive of the error.

## Actual result
The subtitle of the error message is just "Farm".

## Steps to Reproduce
1. Set the map generation settings as follows:
![image](https://user-images.githubusercontent.com/37945304/87653655-72114400-c71b-11ea-9fd9-2c2c7a72047e.png)
2. Use the NewGRFs "Improved Town Layouts" and "Improved Town Industries" with the given parameters and versions.
3. Click "Generate".
4. A warning shows saying that no Coal Mines could be placed.
5. Set the primary industry construction method to "As other industries".
6. Attempt to build any primary industry.
7. The error message is "Can't construct this industry type here ... Farm".

**Comment by 2TallTyler** [comment]
Coal mines probably aren’t generating because they require elevation += 2. I will add a default-off parameter to enable this requirement for those who play on hillier maps and want the rule active. 

I will test the “farm” message. Not sure what’s going on there. 

Did you set the industry density in the NewGRF parameters to match the new game window? This shouldn’t affect funded industries but I’d like to test with the same settings as you.

**Comment by James103** [comment]
I can verify that even if I set the parameters in the NewGRF to match that in the game settings, the same bug occurs. This also affects the scenario editor.
From NewGRF settings:
![image](https://user-images.githubusercontent.com/37945304/87676595-697e3500-c73e-11ea-9ce4-0897ea2da762.png)

From world generation window:
![image](https://user-images.githubusercontent.com/37945304/87676675-8581d680-c73e-11ea-94ae-471cb330abe3.png)
