### ISSUE TITLE
(Question) Factory and paper mill

### ISSUE THREAD

**Issue by Greentaily** [2TallTyler/improved_town_industries#47]
Is there any difference between the two regarding wood besides the additional step with lumber in this version?

It seems that before this version there wasn't any difference at all (except the introduction date I suppose), so choosing one over another would come down to preference. In this version, as I understand it the additional step in the factory chain makes it generate much more profit. Does paper mill compensate the lost potential profit when choosing it over factory somehow?

It could be a nice idea regardless. Since paper mill gets introduced almost a century later, it could have a minor advantage the same way transporting waste to recycling center is more efficient than transporting it to farm directly, in this version.

**Comment by 2TallTyler** [comment]
Yes, your understanding is correct. A Forest->Sawmill->Factory->Houses chain will make more income than Forest->Paper Mill->Houses, since you get to transport another stage of things. 

On the other hand, Paper Mills give you high-value Goods with less initial investment since the chain is simpler. This could be a good starting strategy, or helpful when using citybuilder gamescripts which require certain cargos for town growth.

Simplicity is an important goal of this project, so most industries have a 1:1 conversion rate and will produce an output even with only partial inputs (for example, Paper Mills produce Goods even when only Chemicals are delivered). This is an intentional decision, even if it produces somewhat unrealistic behavior. Perhaps they're getting the Wood by another, not-simulated, trucking company?

Does that answer your question?

**Comment by Greentaily** [comment]
Yes, thank you.
