### ISSUE TITLE
Cannot transport "food" via train, no carriages available; carriages incorrectly labelled

### ISSUE THREAD

**Issue by BattleBirch** [2TallTyler/improved_town_industries#79]
I cannot transport food goods via train since there are no carriages available that can hold it. See picture attached for reproduction. I also tried with the normal start date (year 1950) with the same result.

![image](https://user-images.githubusercontent.com/30420957/132262808-cec0c950-626e-4bd8-9f3c-5597392e23b6.png)

What I also noticed is some carriages have misleading names: e.g. lumber is carried in a livestock car and chemicals in a grain hopper, which doesnt particularly affect the playability though.
 
My installed mods are, in that order: 
OpenGFXBigGUI 2.0.0
Improved Town Industries 1.7.8
Improved Town Layouts 1.4.0

 Apart from these bugs I really enjoy this mod, thank you very much

**Comment by BattleBirch** [comment]
So I disabled Improved Town Layouts to see if that'd help but the result is still the same. 
It looks like I can at least refit trains to transport food if I start from the year 1980, see screenshot below

![image](https://user-images.githubusercontent.com/30420957/132264119-85006d4e-d1b8-4693-807a-6ddc46f86151.png)

**Comment by 2TallTyler** [comment]
This is a long-standing bug in OpenTTD where vanilla vehicles can't transport NewGRF cargos. However, it is fixed in the upcoming 1.12 update, which is currently in beta. 

You have two options: 
1. Download the 1.12 beta through Steam (if using Steam) or from the OpenTTD website
2. Use NewGRF vehicle sets which support NewGRF cargos. OpenGFX+ Trains is vanilla trains with such compatibility, or there are a wide range of additional vehicle sets. My favorites are Mop's Generic Road Vehicles (trucks, buses, and trams), Iron Horse 2 (trains), and Unsinkable Sam (ships).
