### ISSUE TITLE
No time restrictions to the industries. 

### ISSUE THREAD

**Issue by Limyx826** [2TallTyler/improved_town_industries#91]
In previous version, there is a time period when a certain industry will popped up. Now in version 2, there is none at all. In 1700, you can see oil wells when you are not supposed to. Not to mention from the looks of the new documentations, this feel like intentional design. 

Also what happened to Power Plant chain? 
@2TallTyler if you going for a overhaul to the newGRF, I recommend that you separate version 1 and version 2. Cause personally I like how version 1 works compared to version 2.

**Comment by 2TallTyler** [comment]
To be honest, I intentionally used the same GRFID to effectively hide the old version, since I don't want it floating around Bananas under my name. The original ITI was one of my first mods and I learned a lot from it, but it's not my best work.

If you have an old version that you want to keep using, more power to you (and if you don't, I'm happy to provide a non-Bananas download link).

Industry time periods don't currently work because industries (with the exception of the Bank) do not appear during gameplay, nor do they close. That churn is crucial for industry introduction dates. I could write custom closure code to mirror vanilla secondary industry closure rules (close if no production for five years), but new industries spawning gets tricky with the limit of one secondary industry per city — I might be able to write some clever code to reserve space for industries which haven't been invented yet, but then what happens if a player funds industries in all the reserved towns? The edge cases get messy and I'm loathe to re-implement a feature I don't personally use, but I'll consider it for the future.

The Power Plant chain doesn't fit with the new gameplay design, and I used the sprites elsewhere.
